### ISSUE TITLE
更新文档至最新的 redux-saga 版本

### ISSUE THREAD

**Issue by superRaytin** [superRaytin/redux-saga-in-chinese#4]
贡献指南：
1. fork [redux-saga-in-chinese](https://github.com/superRaytin/redux-saga-in-chinese/) & `git clone` 
2. 在 `master` 基础上创建一个分支，比如 `sync-introduction-beginner-tutorial`
3. `npm i && npm run watch`
4. 到 [issues](https://github.com/superRaytin/redux-saga-in-chinese/issues) 列表查找任务，回复认领
5. 找到具体的章节，如 `docs/introduction/BeginnerTutorial.md`
6. 翻译它，参考 [ETC 翻译规范](https://github.com/react-guide/ETC)
7. 完成后，发 PR  到 `0.11.0` 分支
8. 如果一切 OK，PR 会尽快被合并

**Comment by superRaytin** [comment]
0.9.5 文档整体已翻译完。

同步工作已开始：

## 任务分解
- [x] 自述(README.md) #6 
- [ ] 介绍(/docs/introduction/README.md) #7
  - [x] 初级教程(/docs/introduction/BeginnerTutorial.md) #7
  - [ ] Saga 的背景(/docs/introduction/SagaBackground.md) #7
- [ ] 基本概念(/docs/basics/README.md) #8
  - [ ] 使用 Saga 辅助函数(/docs/basics/UsingSagaHelpers.md) #8
  - [ ] 声明式 Effects(/docs/basics/DeclarativeEffects.md) #8
  - [ ] 发起 action(/docs/basics/DispatchingActions.md) #9
  - [ ] 错误处理(/docs/basics/ErrorHandling.md) #9
  - [ ] 一个常见的抽象概念: Effect(/docs/basics/Effect.md) #9
- [ ] 高级(/docs/advanced/README.md) #10
  - [ ] 监听未来的 action(/docs/advanced/FutureActions.md) #10
  - [ ] 无阻塞调用(/docs/advanced/NonBlockingCalls.md) #10
  - [ ] 同时执行多个任务(/docs/advanced/RunningTasksInParallel.md) #10
  - [ ] 在多个 Effects 之间启动 race(/docs/advanced/RacingEffects.md) #11
  - [ ] 通过 yield\* 对 Sagas 进行排序(/docs/advanced/SequencingSagas.md) #11
  - [ ] 组合 Sagas(/docs/advanced/ComposingSagas.md) #11
  - [ ] 任务的取消(/docs/advanced/TaskCancellation.md) #12
  - [ ] 常见的并发模式(/docs/advanced/Concurrency.md) #12
  - [ ] Sagas 测试示例(/docs/advanced/Testing.md) #12
  - [ ] 连接 Sagas 至外部输入和输出(/docs/advanced/UsingRunSaga.md) #12
- [ ] 技巧(/docs/recipes/README.md) #13
- [ ] 外部资源(/docs/ExternalResources.md) #13
- [ ] 问题解答(/docs/Troubleshooting.md) #14
- [ ] 名词解释(/docs/Glossary.md) #15
- [ ] API 参考(/docs/api/README.md) #16

**Comment by colinshen** [comment]
翻译工作有没有时间限制？

**Comment by superRaytin** [comment]
@colinshen 没有时间限制，翻译者自由安排。不过尽量不要拖得太久... 😄

**Comment by colinshen** [comment]
@superRaytin 以前并没有干过这事。看到有翻译规范。不过具体该怎么做？

**Comment by superRaytin** [comment]
目前的工作是**同步文档**，可以点击上面列出的具体的 issue 中去认领，对照官方文档，将相应文档同步至最新。

**Comment by colinshen** [comment]
@superRaytin 懂了。下周我应该有时间。如果有些章节没人认领。我就认领了
