### ISSUE TITLE
文档同步（v1.0.0-beta）

### ISSUE THREAD

**Issue by superRaytin** [superRaytin/redux-saga-in-chinese#46]
现在的文档版本过于老旧（基于 v0.9.5），已经无法跟上社区的步伐，现启动同步至官方最新文档的工作。

由于个人时间有限，现招募志愿者一起来完成这项工作。欢迎认领翻译任务，为 redux-saga 中文社区作出贡献，翻译工作完成后，所有贡献者将会列在本项目首页，还等什么！

## 贡献

志愿者必须具备一定的英语水平。如果你想成为一个志愿者，在本 issue 中留言如 `认领 advanced/Channels.md`，然后我会更新本 issue，在你认领的任务标注志愿者名字并@。同时招募审稿人（reviewer），目前审稿人为 @superRaytin

工作步骤：

1. fork [redux-saga-in-chinese](https://github.com/superRaytin/redux-saga-in-chinese/) & git clone
2. 在 `redux-saga-in-chinese:1.0.0` 基础上创建一个分支，比如 `sync-advanced-channels`
3. `npm i && npm run watch`
3. 翻译认领的任务，参考 [ETC 翻译规范](https://github.com/react-guide/ETC)
4. 翻译完成后，发 PR  到 `redux-saga-in-chinese:1.0.0` 分支
5. 如果一切 OK，PR 会尽快被合并

### TODOs

- [x] readme.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/README.md) @superRaytin
- [x] ExternalResources.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/ExternalResources.md) @superRaytin
- [x] Glossary.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/Glossary.md) @superRaytin
- [x] Troubleshooting.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/Troubleshooting.md) @superRaytin

> advanced

- [x] advanced/README.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/README.md) @superRaytin
- [x] advanced/Channels.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Channels.md) @superRaytin
- [x] advanced/ComposingSagas.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/ComposingSagas.md) @superRaytin
- [x] advanced/Concurrency.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Concurrency.md) @superRaytin
- [x] advanced/ForkModel.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/ForkModel.md) @superRaytin
- [x] advanced/FutureActions.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/FutureActions.md) @superRaytin
- [x] advanced/NonBlockingCalls.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/NonBlockingCalls.md)
- [x] advanced/RacingEffects.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RacingEffects.md)
- [x] advanced/RunningTasksInParallel.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RunningTasksInParallel.md)
- [x] advanced/SequencingSagas.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/SequencingSagas.md)
- [x] advanced/TaskCancellation.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/TaskCancellation.md)
- [x] advanced/Testing.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Testing.md)
- [x] advanced/UsingRunSaga.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/UsingRunSaga.md)

> api

- [x] api/README.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/api/README.md) @imyelo 

> basics

- [x] basics/README.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/README.md) @superRaytin
- [x] basics/DeclarativeEffects.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/DeclarativeEffects.md)
- [x] basics/DispatchingActions.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/DispatchingActions.md)
- [x] basics/Effect.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/Effect.md)
- [x] basics/ErrorHandling.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/ErrorHandling.md)
- [x] basics/UsingSagaHelpers.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/UsingSagaHelpers.md) @Ariel-zhangyue 

> introduction

- [x] introduction/README.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/introduction/README.md) @superRaytin
- [x] introduction/BeginnerTutorial.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/introduction/BeginnerTutorial.md)  @superRaytin
- [x] introduction/SagaBackground.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/introduction/SagaBackground.md) @superRaytin

> recipes

- [x] recipes/README.md [原文](https://github.com/redux-saga/redux-saga/blob/master/docs/recipes/README.md)

已经完成的任务，可以到 [1.0.0](https://github.com/superRaytin/redux-saga-in-chinese/tree/1.0.0) 分支查看

**Comment by Ariel-zhangyue** [comment]
认领 basics/UsingSagaHelpers.md

**Comment by superRaytin** [comment]
@Ariel-zhangyue 已更新 issue，谢谢！

**Comment by antgod** [comment]
认领 api/README.md

**Comment by superRaytin** [comment]
@antgod 已更新 issue，谢谢！

**Comment by imyelo** [comment]
api/README.md 有在翻译吗？

**Comment by superRaytin** [comment]
@imyelo 这个文档暂时没有进度，你愿意翻译吗？

**Comment by imyelo** [comment]
嗯，如果没有在翻的话我认领咯

**Comment by superRaytin** [comment]
@imyelo 已更新 issue，谢谢！翻译完成后及时发 PR~

**Comment by DarwinniwraD** [comment]
@superRaytin 目前哪些部分被认领过了

**Comment by superRaytin** [comment]
@DarwinniwraD 打过勾的是已经认领过并完成了的，目前只剩下 `api/README.md` 未完成

**Comment by DarwinniwraD** [comment]
@superRaytin 哦哦，大致扫了一下，我看接口文档也差不多了 👍 👍

**Comment by superRaytin** [comment]
@imyelo 进度怎么样

**Comment by imyelo** [comment]
@superRaytin 抱歉弄了这么久，今天可以提 PR

**Comment by joeyzone** [comment]
代码跟英文原版都不同啊，完全不能用，仔细检查一下吧，连   sagaMiddleware.run(mySaga) 这一句都少了
